## 根据实际情况来填写这里面的内容,填写完成之后,根据后缀名来放入到 nacos 中去管理.
#### xxx 可以是dev, test, prod 等.

## 配置信息
# Spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/app_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

# Mybatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.application.cloud.job.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*.xml

# swagger 配置
swagger:
  title: 定时任务接口文档
  license: Powered By app-cloud
  licenseUrl: https://app-cloud.vip
  authorization:
    name: Cloud OAuth
    auth-regex: ^.*$
    authorization-scope-list:
      - scope: server
        description: 客户端授权范围
    token-url-list:
      - http://localhost:8080/auth/oauth/token

