spring:
  redis:
    host: localhost
    port: 6379
    password:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: app-cloud-authclient
          uri: lb://app-cloud-authclient
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - ValidateCodeFilter
            - StripPrefix=1
        # 代码生成
        - id: app-cloud-gencode
          uri: lb://app-cloud-gencode
          predicates:
            - Path=/code/**
          filters:
            - StripPrefix=1
        # 定时任务
        - id: app-cloud-jobtask
          uri: lb://app-cloud-jobtask
          predicates:
            - Path=/schedule/**
          filters:
            - StripPrefix=1
        # 系统模块
        - id: app-cloud-system
            uri: lb://app-cloud-system
            predicates:
              - Path=/system/**
            filters:
              - name: BlackListUrlFilter
                args:
                  blacklistUrl:
                    - /user/info/*
              - StripPrefix=1
        # 文件模块
        - id: app-cloud-osscloud
          uri: lb://app-cloud-osscloud
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1