server:
  port: 8888

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.217:3306/datax_web?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1q2w3E4R
    #Oracle配置
    #    driverClassName: oracle.jdbc.OracleDriver
    #    url: jdbc:oracle:thin:@47.100.206.162:1521:xe
    #    username: oracle
    #    password: 123456
    #SQLServer配置
    #    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=renren_fast
    #    username: sa
    #    password: 123456
    #PostgreSQL配置
    #    driverClassName: org.postgresql.Driver
    #    url: jdbc:postgresql://192.168.10.10:5432/renren_fast
    #    username: postgres
    #    password: 123456
  ##jackson 配置.
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

##mongo设置.
#mongodb:
  #host: localhost
  #port: 27017
  #auth: false #是否使用密码验证
  #username: tincery
  #password: Txy123.com
  #source: tincery_pro
  #database: admin


##日志打印.
logging:
  level:
    com.application.cloud: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE


##mybatis-plus配置.
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
    #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# PageHelper分页插件
pagehelper:
  helperDialect: ${generater.database}
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#指定数据库，可选值有[mysql、oracle、sqlserver、postgresql,mongo]
generater:
  database: mysql


